---
- hosts: localhost
  gather_facts: False
  module_defaults:
    community.aws.dynamodb_table:
      aws_access_key: "mock_access_key"
      aws_secret_key: "mock_secret_key"
      region: "us-east-1"
      endpoint_url: "http://localhost:4566"

  tasks:
    - name: Delete dynamodb tables
      community.aws.dynamodb_table:
        name: "{{ item }}"
        state: absent
      loop:
        - ProductCatalog
        - Forum
        - Thread
        - Reply

